namespace SpriteKind {
    export const StatusBar = SpriteKind.create()
}
let runrun = sprites.create(img`
    .a..............a.......
    .b.a..........abb.......
    .bbbaa......aabbb.......
    .bbbaa......aabbb.......
    .bbbbaa.aa.aabbbb.......
    ..bbaaaaaaaaaab.........
    ..aaaaaabbaaaaa.........
    ..aaaffabbaaffa.........
    ..aafffabbafffa.........
    bbbbfffdaadfffbbbb......
    dbbbfffdffdfffbbbd......
    .dbbbbddddddbbbdd.......
    ..ddbbbbbbbbbbdc....d...
    .......aaaa........dddd.
    .....aaaaaaaa.....dddddd
    ....aaabbbbaaa....bdbddb
    ....aaabbbbaaa....bdbddb
    ..dd..abbbba..dc..ababba
    ..aaa.abafba.aa...aaaaaa
    ..aaa.abbbba.aa..aaaaaa.
    .......aaaaaaaaaaaaaa...
    .......a..aaaaaaaaaa....
    .......d..d..aaaaa......
    .......d..d..aaaaa......
    `, SpriteKind.Player)
controller.moveSprite(runrun)
scene.setBackgroundColor(5)
